# Generated by Django 4.0.5 on 2022-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenant_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phno', models.CharField(max_length=32)),
                ('p_addr', models.CharField(max_length=128)),
                ('govtid', models.CharField(max_length=32)),
                ('roomno', models.CharField(max_length=8)),
                ('rent', models.CharField(max_length=32)),
                ('roomsharing', models.IntegerField()),
                ('occupation', models.CharField(max_length=16)),
                ('office_addr', models.CharField(max_length=128)),
                ('office_id', models.CharField(max_length=16)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default=None)),
                ('advance', models.CharField(max_length=32)),
            ],
        ),
    ]
