# Generated by Django 4.0.5 on 2022-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('phno', models.IntegerField()),
                ('p_addr', models.CharField(max_length=128)),
                ('govtid', models.CharField(max_length=32)),
                ('roomno', models.CharField(max_length=8)),
                ('rent', models.IntegerField()),
                ('roomsharing', models.IntegerField()),
                ('occupation', models.CharField(max_length=16)),
                ('office_addr', models.CharField(max_length=128)),
                ('office_id', models.CharField(max_length=16)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('advance', models.IntegerField()),
            ],
        ),
    ]
