# Generated by Django 4.0.5 on 2022-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='advance',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='phno',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='rent',
            field=models.CharField(max_length=32),
        ),
    ]
