# Generated by Django 4.0.5 on 2022-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0003_remove_tenants_tenant_id_alter_tenants_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='id',
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant_id',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
        ),
    ]
