# Generated by Django 4.0.5 on 2022-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0004_remove_tenants_id_tenants_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='tenant_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
